### PR TITLE
incident report generation

### PR DESCRIPTION
**Pull request by umayangag**

### CODE REVIEW

**Comment by ManZzup** [comment]
@umayangag there's a merge conflict on the package.json.lock, can you check it
also remove .idea and venv dir from the commit

**Comment by umayangag** [comment]
Hi Manujith,
Haven't commited .idea and venv directories. I made sure to include them in
the gitignore file. Will resolve the merge issue. Thanks

**Comment by umayangag** [comment]
@ManZzup  conflicts on the package.json.lock have been resolved.

**Comment by ManZzup** [comment]
@umayangag my bad, i saw the .gitignore as dir creations

**Pull request merged**
