### PR TITLE
Resolve #418 #419

### LINKED ISSUE #418: Create inquiry 'box' at the top of form/ separate screen for inquiry-specific information to be collected/typed
Common:
1. Mode of receipt
2. Title
3. Description 
4. Election 

Specific to inquiries:

1. Reference number 
2. Received date
3. Letter date
4. Stamp date
5. Category (6 categories)
6. Institution

**// don't add the rest from here**
7. Decision 
8. Signatory Name 
9. Signatory Designation

### PR DESCRIPTION
**Pull request by thivi**
This resolves #418 #419 

Inquiry Screen
image
image

Complaint Screen
image
image

### CODE REVIEW

**Comment by thivi** [comment]
Complaint details
image

Inquiry Details
image

**Comment by MrClemRkz** [comment]
- [ ] I just got clarified with EC we dont' need both `received date` and `stamp date`. will have only the  `received date`.

**Comment by thivi** [comment]
image

**Comment by MrClemRkz** [comment]
merging this with issues. will be changed on the next commit.

**Pull request merged**
